### ISSUE TITLE
veo_proc_create fails at 2nd attempt

### ISSUE THREAD

**Issue by kaz7** [veos-sxarr-NEC/veoffload#2]
Hi,

When I wrote a program to call veo_proc_create multiple times, veo_proc_create was failed at 2nd attempt every time.  Is there any workaround to avoid this?  Should I not destroy a proc even if 2nd call for the calculation may be not invoked for a while?  Thanks.

example:
```
#include <stdio.h>
#include <stdlib.h>
#include <ve_offload.h>
int main()
{
  struct veo_proc_handle *proc = veo_proc_create(0);
  if (proc == NULL) {
    fprintf(stderr, "veo_proc_create is failed 1st attempt\n");
    perror("veo_proc_create");
    exit(1);
  }
  int err = veo_proc_destroy(proc);
  if (err != 0) {
    fprintf(stderr, "veo_proc_destroy is failed 1st attempt\n");
    perror("veo_proc_destroy");
    exit(1);
  }
  proc = veo_proc_create(0);
  if (proc == NULL) {
    fprintf(stderr, "veo_proc_create is failed 2nd attempt\n");  // failed here every time
    perror("veo_proc_create");
    exit(1);
  }
  err = veo_proc_destroy(proc);
  if (err != 0) {
    fprintf(stderr, "veo_proc_destroy is failed 2nd attempt\n");
    perror("veo_proc_destroy");
    exit(1);
  }
  return 0;
}
```

**Comment by veos-sxarr** [comment]
Hello,

Thank you for your comment.
Due to current VEO implementation, veo_proc_create() can not be called multiple times. However, it can be avoided by reusing the same process without destroying the process.
This restriction corresponds to the fourth of Restriction.
<https://veos-sxarr-nec.github.io/veoffload/md_Restriction.html>

**Comment by kaz7** [comment]
Thank you so much for the reply.  I'll change my programs.
