### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by noma** [veos-sxarr-NEC/veoffload#3]
I'm getting the following compiler warnings using g++ to compile the the host code.

```terminal
/opt/nec/ve/veos/include/ve_offload.h:106:31: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 const int veo_api_version(void);
                               ^
```

While the `const` is not technically wrong, it has no effect here, but it will fail builds with `-Werror`, e.g. often used for continuous integration.

**Comment by veos-sxarr** [comment]
Thank you for reporting the issue.
We will release the header with `const` here removed in next release.

**Comment by veos-sxarr** [comment]
Version 2.2.2 with this fix is now released.
